### ISSUE TITLE
noto serif ottoman siyaq: latin is sans

### ISSUE THREAD

**Issue by eliheuer** [notofonts/ottoman-siyaq-numbers#4]
This is on fonts.google.com as `noto serif ottoman siyaq`, but the latin is sans. See screenshot below:

![Screenshot 2023-07-31 at 11 50 31 PM](https://github.com/notofonts/ottoman-siyaq-numbers/assets/5162664/884f7128-3ec5-4d73-89fd-f39099d33ead)

![Screenshot 2023-07-31 at 11 43 59 PM](https://github.com/notofonts/ottoman-siyaq-numbers/assets/5162664/85fb40b9-4a3d-4df2-a8dc-e3935dbefbeb)

**Comment by simoncozens** [comment]
Thanks. This is the same bug as #3, isn't it? This was fixed in the sources but I've just released 1.006 so that it can be onboarded to google/fonts. (I tend to only release every quarter to avoid overloading the onboarders, but if this is messing up categorization I figure let's fix it now. The font should be considered a serif.)

**Comment by eliheuer** [comment]
Thanks Simon, yes this is same as #3 and the main reason for this issue is that this has caused a lot of confusion in the new categorization effort.
